# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "LIIR | Journal Club"
name:  "Journal Club"
email: liir-journal-org@kuleuven.be
description: "Hosting all information Regarding the Journal-Club events: reading-club and seminar sessions."
minimal_mistakes_skin: default
search: true
locale: "en"
URL: "https://liir-kuleuven.github.io"
logo: "/assets/images/LIIR_journal_club.png"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
future: true

atom_feed:
  hide: true


# Pagination
paginate: 3 # amount of posts to show
paginate_path: /journal-club/seminars/page:num/
timezone: Europe/Brussels # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _journalclub

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

footer:
  links:
    - label: "E-Mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:liir-journal-org@kuleuven.be"
    - label: "Slack | LIIR#journalclub"
      icon: "fab fa-fw fa-slack"
      url: "https://liir.slack.com/messages/journalclub/"

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: "_journalclub"
    values:
      layout: single
      classes: wide2
      read_time: false
      author_profile: false
      share: false
      comments: false
  # _seminars
  - scope:
      path: "_seminars"
    values:
      show_date: true
      layout: single
      classes: wide2
      read_time: false
      author_profile: false
      share: false
      comments: true
      future: true

collections:
  seminars:
    sort_by: date
    sort_order: reverse
    output: true
    future: true
    permalink: /journal-club/:collection/:path/
theme: jekyll-theme-minimal
